### ISSUE TITLE
[Cesiumn-Version] Updating the Cesium version (1.73 -> 1.108.0)

### ISSUE THREAD

**Issue by breeze0512** [aistairc/mf-cesium#52]
1. Updating the previously used cesium to the latest version

- [ ] Cesium version update using npm
- [ ] Check whether existing Stinuum UI is compatible
- [ ] Check whether existing Stinuum functions are available or not

**Comment by breeze0512** [comment]
> [!WARNING]  
> An error occurs when turning on/off the visualized MovingFeature.

```
An error occurred while rendering.  Rendering has stopped.
TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Sf.update (http://localhost:8080/cesium/Build/Cesium/Cesium.js:8325:308046)
    at Ri._onTick (http://localhost:8080/cesium/Build/Cesium/Cesium.js:14476:112605)
    at nw.raiseEvent (http://localhost:8080/cesium/Build/Cesium/Cesium.js:95:1282)
    at G9.tick (http://localhost:8080/cesium/Build/Cesium/Cesium.js:8325:43587)
    at OT.render (http://localhost:8080/cesium/Build/Cesium/Cesium.js:14432:1612)
    at n (http://localhost:8080/cesium/Build/Cesium/Cesium.js:14430:8645)
Cesium.js:8325 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'add')
    at Sf._onDataSourceAdded (Cesium.js:8325:309337)
    at nw.raiseEvent (Cesium.js:95:1282)
    at Cesium.js:8325:106087
Cesium.js:8325 Uncaught TypeError: Cannot read properties of undefined (reading 'remove')
    at Sf._onDataSourceRemoved (Cesium.js:8325:309544)
    at nw.raiseEvent (Cesium.js:95:1282)
    at Fc.removeAll (Cesium.js:8325:106465)
    at Stinuum.GeometryViewer.clear (stinuum.js:518:45)
    at Stinuum.GeometryViewer.update (stinuum.js:504:10)
    at drawFeatures (Print.js:171:28)
    at afterChangingCheck (List.js:82:3)
    at toggleFeature (Print.js:161:5)
    at HTMLInputElement.<anonymous> (DivListMaker.js:117:7)
```

**Comment by breeze0512** [comment]
1. If multiple mfs are visualized, a timeout error occurs during the graph display process.
